# Generated by Django 4.2 on 2026-01-17 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("data", "0001_initial"),
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_str_prompt", models.TextField()),
                ("query_options", models.JSONField(null=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data.collectionofdocuments",
                    ),
                ),
                (
                    "organisation_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="system.organisationuser",
                    ),
                ),
                ("query_templates", models.ManyToManyField(to="data.querytemplate")),
            ],
        ),
        migrations.CreateModel(
            name="UserQueryResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("general_stats_json", models.JSONField()),
                ("detailed_results_json", models.JSONField()),
                ("structured_results", models.JSONField(null=True)),
                (
                    "user_query",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="engine.userquery",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserQueryResponseAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_generative", models.BooleanField()),
                ("answer_options", models.JSONField()),
                ("query_instruction_prompt", models.TextField(null=True)),
                ("generated_answer", models.TextField(null=True)),
                ("generated_answer_translated", models.TextField(null=True)),
                ("extractive_qa_result_json", models.JSONField(null=True)),
                ("generative_qa_result_json", models.JSONField(null=True)),
                ("rate_value", models.IntegerField(null=True)),
                ("rate_nax_value", models.IntegerField(null=True)),
                ("rate_comment", models.TextField(null=True)),
                ("generation_time", models.DurationField(null=True)),
                (
                    "user_response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="engine.userqueryresponse",
                    ),
                ),
            ],
        ),
    ]
