"""
models.py
---------

Django ORM model definitions used by the search engine.  The models
represent user‑submitted queries, the corresponding responses and the
answers generated (either extractive or generative).  They are linked
to the core data models such as ``OrganisationUser`` and
``CollectionOfDocuments``.
"""

from django.db import models

from data.models import (
    OrganisationUser,
    CollectionOfDocuments,
    QueryTemplate,
    DocumentPageText,
)


class UserQuery(models.Model):
    """
    Stores a single query submitted by a user.

    Attributes
    ----------
    organisation_user : OrganisationUser
        Reference to the user who issued the query.
    collection : CollectionOfDocuments
        The collection of documents that the query is executed against.
    query_str_prompt : str
        The raw text entered by the user.
    query_options : dict
        JSON‑serialisable options that influence the search (filters,
        ranking flags, etc.).
    query_templates : ManyToMany[QueryTemplate]
        Templates selected for this query – used for structured responses.
    """

    # pk: auto-id

    organisation_user = models.ForeignKey(
        OrganisationUser, null=False, on_delete=models.PROTECT
    )
    collection = models.ForeignKey(
        CollectionOfDocuments, null=False, on_delete=models.PROTECT
    )

    query_str_prompt = models.TextField(null=False, blank=False)
    query_options = models.JSONField(null=True, blank=False)

    query_templates = models.ManyToManyField(QueryTemplate)


class UserQueryResponse(models.Model):
    """
    Persists the result of a ``UserQuery`` execution.

    Attributes
    ----------
    user_query : UserQuery
        The query that produced this response.
    general_stats_json : dict
        High‑level statistics (e.g. number of hits, scores).
    detailed_results_json : dict
        Full result set with individual text fragments.
    structured_results : dict | None
        Optional structured data extracted according to a template.
    """

    # pk: auto-id

    user_query = models.ForeignKey(UserQuery, null=False, on_delete=models.PROTECT)

    general_stats_json = models.JSONField(null=False)
    detailed_results_json = models.JSONField(null=False)
    structured_results = models.JSONField(null=True)


class UserQueryResponseAnswer(models.Model):
    """
    Represents a single answer belonging to a ``UserQueryResponse``.

    The answer can be either generative (produced by an LLM) or
    extractive (taken directly from source documents).  Rating fields
    allow the user to provide feedback.

    Attributes
    ----------
    user_response : UserQueryResponse
        Parent response.
    is_generative : bool
        ``True`` if the answer was generated by a model.
    answer_options : dict
        Additional options (e.g. model name, temperature).
    query_instruction_prompt : str | None
        Prompt that was sent to the generative model, if applicable.
    generated_answer : str | None
        Text produced by the generative model.
    generated_answer_translated : str | None
        Translated version of the generated answer.
    extractive_qa_result_json : dict | None
        Raw QA extraction data.
    generative_qa_result_json : dict | None
        Raw generative QA data.
    rate_value : int | None
        User‑provided rating (e.g. 1‑5).
    rate_nax_value : int | None
        Maximum possible rating value.
    rate_comment : str | None
        Optional free‑form comment from the user.
    generation_time : datetime.timedelta | None
        Time taken by the model to generate the answer.
    """

    user_response = models.ForeignKey(
        UserQueryResponse, null=False, on_delete=models.PROTECT
    )
    is_generative = models.BooleanField(null=False)
    answer_options = models.JSONField(null=False, blank=False)

    query_instruction_prompt = models.TextField(null=True)

    generated_answer = models.TextField(null=True)
    generated_answer_translated = models.TextField(null=True)

    extractive_qa_result_json = models.JSONField(null=True)
    generative_qa_result_json = models.JSONField(null=True)

    rate_value = models.IntegerField(null=True)
    rate_nax_value = models.IntegerField(null=True)
    rate_comment = models.TextField(null=True)

    generation_time = models.DurationField(null=True)


#
#
# class UserQueryResultsBox(models.Model):
#     # pk: auto-id
#
#     organisation_user = models.ForeignKey(
#         OrganisationUser, null=False, on_delete=models.PROTECT
#     )
#     collection = models.ForeignKey(
#         CollectionOfDocuments, null=False, on_delete=models.PROTECT
#     )
#
#     name = models.TextField(null=True)
#     description = models.TextField(null=True)
#     note = models.TextField(null=True)
#
#     is_private = models.BooleanField(null=False, default=True)
#
#
# class DocumentPageTextInUserQueryResultsBox(models.Model):
#     results_box = models.ForeignKey(
#         UserQueryResultsBox, null=False, on_delete=models.PROTECT
#     )
#     found_text = models.ForeignKey(
#         DocumentPageText, null=False, on_delete=models.PROTECT
#     )
#
#     # Optional fields
#     user_query_str = models.TextField(null=True)
#     user_query_response = models.ForeignKey(
#         UserQueryResponse, null=True, on_delete=models.PROTECT
#     )
#
#     class Meta:
#         unique_together = ("results_box", "found_text")
