# Generated by Django 4.2.27 on 2026-10-09 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionState",
            fields=[
                ("state", models.TextField(primary_key=True, serialize=False)),
                ("session_state", models.TextField(null=True)),
                ("grant_code", models.TextField(null=True)),
                ("state_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acc_token", models.TextField()),
                ("is_active", models.BooleanField(default=False)),
                ("acc_created", models.DateTimeField(auto_now_add=True)),
                ("not_before_policy", models.IntegerField(null=True)),
                ("expires_in", models.IntegerField(null=True)),
                ("refresh_expires_in", models.IntegerField(null=True)),
                ("token_type", models.TextField(null=True)),
                ("refresh_token", models.TextField(null=True)),
                ("scope", models.TextField(null=True)),
                ("decoded_token", models.JSONField(null=True)),
                (
                    "auth_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authorization.sessionstate",
                    ),
                ),
            ],
        ),
    ]
