from django.db import models

from engine.models import UserQuery, UserQueryResponse, UserQueryResponseAnswer
from data.models import OrganisationUser, CollectionOfDocuments


class Chat(models.Model):
    """
    A conversation instance belonging to an organisation user.

    Attributes
    ----------
    organisation_user : OrganisationUser
        The user (or organisation) that owns the chat.  ``PROTECT`` is used
        to avoid accidental cascade deletion of chats when a user is removed.
    collection : CollectionOfDocuments | None
        Optional reference to a collection of documents that can be used for
        Retrieval‑Augmented Generation.  ``null=True`` means the chat may be
        purely generative.
    created_at : datetime
        Timestamp automatically set when the chat is first created.
    options : dict | None
        JSON‑serialisable dictionary storing arbitrary generation options
        supplied by the client (e.g. temperature, top‑p).
    search_options : dict | None
        Options that influence the vector‑store search performed during RAG.
    hash : str | None
        A stable hash value used to retrieve a saved (read‑only) chat.
    is_saved : bool
        Marks whether the chat has been explicitly saved.  Saved chats are
        typically read‑only and can be fetched later via the hash.
    read_only : bool
        When ``True`` the chat cannot accept new messages; attempts to add
        messages will raise an error.
    """

    # pk: auto-id

    organisation_user = models.ForeignKey(
        OrganisationUser, null=False, on_delete=models.PROTECT
    )
    collection = models.ForeignKey(
        CollectionOfDocuments, null=True, on_delete=models.PROTECT
    )

    created_at = models.DateTimeField(auto_now_add=True)
    options = models.JSONField(null=True)
    search_options = models.JSONField(null=True)

    hash = models.TextField(null=True)
    is_saved = models.BooleanField(default=False, null=False)
    read_only = models.BooleanField(default=False, null=False)


class ContentSupervisorState(models.Model):
    """
    State produced by the content‑supervisor component.

    This model captures the type of supervision performed and any JSON
    payload that the supervisor returns (e.g. flagged content, suggested
    edits, etc.).

    Attributes
    ----------
    state_type : str
        Identifier of the supervision type (e.g. ``"moderation"``,
        ``"fact_check"``).
    www_content : dict | None
        Arbitrary JSON data returned by the supervisor; ``null`` when no
        extra data is needed.
    """

    # pk: auto-id

    state_type = models.TextField(null=False)

    www_content = models.JSONField(null=True)


class RAGMessageState(models.Model):
    """
    Metadata describing how a message was generated via RAG.

    The fields store whether the message contains a query or an instruction,
    the extracted textual fragments, and the relationships to the underlying
    ``engine`` query/response objects.

    Attributes
    ----------
    contains_query : bool
        ``True`` if the assistant message embeds a user query.
    contains_instruction : bool
        ``True`` if the message contains an explicit instruction for the model.
    extracted_query : str | None
        The raw query text that was extracted from the user input.
    extracted_instruction : str | None
        The raw instruction text extracted from the user input.
    sse_query : UserQuery | None
        Reference to the stored ``UserQuery`` object (if any).
    sse_response : UserQueryResponse | None
        The response generated by the search‑engine for the query.
    sse_answer : UserQueryResponseAnswer | None
        The final answer selected from the response set.
    system_prompt : str | None
        Optional system prompt that was injected for this generation step.
    """

    # pk: auto-id

    contains_query = models.BooleanField(null=False)
    contains_instruction = models.BooleanField(null=False)

    extracted_query = models.TextField(null=True)
    extracted_instruction = models.TextField(null=True)

    sse_query = models.ForeignKey(
        UserQuery,
        null=True,
        on_delete=models.PROTECT,
    )
    sse_response = models.ForeignKey(
        UserQueryResponse, null=True, on_delete=models.PROTECT
    )
    sse_answer = models.ForeignKey(
        UserQueryResponseAnswer, null=True, on_delete=models.PROTECT
    )

    system_prompt = models.TextField(null=True)


class MessageState(models.Model):
    """
    Container linking a message to its RAG and content‑supervisor states.

    A ``MessageState`` may reference a ``RAGMessageState`` and/or a
    ``ContentSupervisorState``.  Both relationships are optional because a
    message might be purely generative or might not have undergone any
    supervision.

    Attributes
    ----------
    rag_message_state : RAGMessageState | None
        The RAG‑related metadata for the message.
    content_supervisor_state : ContentSupervisorState | None
        The supervision metadata for the message.
    """

    # pk: auto-id

    rag_message_state = models.ForeignKey(
        RAGMessageState, null=True, on_delete=models.PROTECT
    )

    content_supervisor_state = models.ForeignKey(
        ContentSupervisorState, null=True, on_delete=models.PROTECT
    )


class Message(models.Model):
    """
    A single utterance within a ``Chat``.

    Each message records its role (e.g. ``"user"`` or ``"assistant"``),
    textual content, ordering information, and optional links to the
    previous/next messages to enable linear traversal.

    Attributes
    ----------
    chat : Chat
        The chat to which this message belongs.
    role : str
        Identifier of the speaker (commonly ``"user"``, ``"assistant"``,
        ``"system"``, etc.).
    text : str
        Raw message text as supplied or generated.
    text_translated : str | None
        Optional translation of ``text`` into another language.
    number : int
        Sequential index of the message within the chat; together with
        ``chat`` and ``role`` forms a unique constraint.
    date_time : datetime
        Timestamp automatically set at creation.
    state : MessageState | None
        Link to the auxiliary state objects (RAG, supervision).
    options : dict | None
        Generation options specific to this message.
    search_options : dict | None
        Search options used if the message was generated via RAG.
    prev_message : Message | None
        Reference to the immediately preceding message (if any).
    next_message : Message | None
        Reference to the immediately succeeding message (if any).
    generation_time : timedelta | None
        How long the model took to generate the assistant message.
    """

    # pk: auto-id

    chat = models.ForeignKey(Chat, null=False, on_delete=models.PROTECT)
    role = models.CharField(max_length=32, null=False)

    text = models.TextField(null=False)
    text_translated = models.TextField(null=True)
    number = models.IntegerField(null=False)

    date_time = models.DateTimeField(auto_now_add=True)

    state = models.ForeignKey(MessageState, null=True, on_delete=models.PROTECT)
    options = models.JSONField(null=True)
    search_options = models.JSONField(null=True)

    prev_message = models.ForeignKey(
        "Message",
        null=True,
        on_delete=models.CASCADE,
        related_name="msg_prev_message",
    )

    next_message = models.ForeignKey(
        "Message",
        null=True,
        on_delete=models.CASCADE,
        related_name="msg_next_message",
    )

    generation_time = models.DurationField(null=True)

    class Meta:
        unique_together = ("chat", "role", "number")
