# Generated by Django 4.2 on 2026-01-17 00:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionOfDocuments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("display_name", models.TextField()),
                ("description", models.TextField(null=True)),
                ("model_embedder", models.TextField(null=True)),
                ("model_reranker", models.TextField(null=True)),
                ("model_embedder_vector_size", models.IntegerField(null=True)),
                ("embedder_index_type", models.TextField(null=True)),
                ("embedder_index_params", models.TextField(null=True)),
                ("embedder_search_params", models.TextField(null=True)),
                (
                    "created_on",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="system.organisationuser",
                    ),
                ),
                (
                    "visible_to_groups",
                    models.ManyToManyField(to="system.organisationgroup"),
                ),
            ],
            options={
                "unique_together": {("name", "created_by")},
            },
        ),
        migrations.CreateModel(
            name="CollectionOfQueryTemplates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                (
                    "created_on",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="system.organisation",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "organisation")},
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("path", models.TextField()),
                ("relative_path", models.TextField()),
                ("document_hash", models.TextField()),
                ("use_in_search", models.BooleanField(default=True)),
                (
                    "created_on",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("category", models.TextField(null=True)),
                ("metadata_json", models.JSONField(null=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="system.organisationuser",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data.collectionofdocuments",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_number", models.IntegerField()),
                (
                    "created_on",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data.document",
                    ),
                ),
            ],
            options={
                "unique_together": {("document", "page_number")},
            },
        ),
        migrations.CreateModel(
            name="UploadedDocuments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dir_hash", models.TextField(unique=True)),
                ("dir_path", models.TextField()),
                (
                    "created_on",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_indexed", models.BooleanField(default=False)),
                ("begin_indexing_time", models.DateTimeField(null=True)),
                ("end_indexing_time", models.DateTimeField(null=True)),
                ("number_of_uploaded_documents", models.IntegerField(null=True)),
                (
                    "number_of_indexed_documents_rel_db",
                    models.IntegerField(null=True),
                ),
                (
                    "number_of_indexed_documents_vec_db",
                    models.IntegerField(null=True),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="system.organisationuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QueryTemplateGrammar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tokens", models.JSONField()),
                ("alphabet", models.JSONField()),
                (
                    "template_collection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data.collectionofquerytemplates",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="document",
            name="upload_process",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="data.uploadeddocuments",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="visible_to_groups",
            field=models.ManyToManyField(to="system.organisationgroup"),
        ),
        migrations.CreateModel(
            name="QueryTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("display", models.TextField(null=True)),
                ("data_connector", models.JSONField(null=True)),
                ("data_filter_expressions", models.JSONField(null=True)),
                ("structured_response_if_exists", models.BooleanField(null=True)),
                ("structured_response_data_fields", models.JSONField(null=True)),
                ("system_prompt", models.TextField(null=True)),
                (
                    "template_grammar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data.querytemplategrammar",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "template_grammar")},
            },
        ),
        migrations.CreateModel(
            name="DocumentPageText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_number", models.IntegerField()),
                ("text_str", models.TextField()),
                ("text_str_clear", models.TextField(null=True)),
                ("text_hash", models.TextField()),
                ("text_chunk_type", models.TextField()),
                ("language", models.TextField()),
                ("metadata_json", models.JSONField(null=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data.documentpage",
                    ),
                ),
                (
                    "paged_text",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data.documentpagetext",
                    ),
                ),
            ],
            options={
                "unique_together": {("text_number", "page", "text_chunk_type")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="document",
            unique_together={("name", "collection", "path", "document_hash")},
        ),
    ]
