# Generated by Django 4.2 on 2026-01-17 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("engine", "0001_initial"),
        ("data", "0001_initial"),
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("options", models.JSONField(null=True)),
                ("search_options", models.JSONField(null=True)),
                ("hash", models.TextField(null=True)),
                ("is_saved", models.BooleanField(default=False)),
                ("read_only", models.BooleanField(default=False)),
                (
                    "collection",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data.collectionofdocuments",
                    ),
                ),
                (
                    "organisation_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="system.organisationuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContentSupervisorState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state_type", models.TextField()),
                ("www_content", models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RAGMessageState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contains_query", models.BooleanField()),
                ("contains_instruction", models.BooleanField()),
                ("extracted_query", models.TextField(null=True)),
                ("extracted_instruction", models.TextField(null=True)),
                ("system_prompt", models.TextField(null=True)),
                (
                    "sse_answer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="engine.userqueryresponseanswer",
                    ),
                ),
                (
                    "sse_query",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="engine.userquery",
                    ),
                ),
                (
                    "sse_response",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="engine.userqueryresponse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MessageState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_supervisor_state",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="chat.contentsupervisorstate",
                    ),
                ),
                (
                    "rag_message_state",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="chat.ragmessagestate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=32)),
                ("text", models.TextField()),
                ("text_translated", models.TextField(null=True)),
                ("number", models.IntegerField()),
                ("date_time", models.DateTimeField(auto_now_add=True)),
                ("options", models.JSONField(null=True)),
                ("search_options", models.JSONField(null=True)),
                ("generation_time", models.DurationField(null=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="chat.chat"
                    ),
                ),
                (
                    "next_message",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="msg_next_message",
                        to="chat.message",
                    ),
                ),
                (
                    "prev_message",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="msg_prev_message",
                        to="chat.message",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="chat.messagestate",
                    ),
                ),
            ],
            options={
                "unique_together": {("chat", "role", "number")},
            },
        ),
    ]
