# Generated by Django 4.2 on 2026-01-17 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organisation",
            fields=[
                ("name", models.TextField(primary_key=True, serialize=False)),
                ("description", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrganisationGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_name", models.TextField()),
                ("description", models.TextField(null=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="system.organisation",
                    ),
                ),
            ],
            options={
                "unique_together": {("group_name", "organisation")},
            },
        ),
        migrations.CreateModel(
            name="OrganisationUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "auth_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="system.organisation",
                    ),
                ),
                (
                    "user_groups",
                    models.ManyToManyField(to="system.organisationgroup"),
                ),
            ],
        ),
    ]
